[env:WIST]

; --- (CORE 3.0+) ---
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor
monitor_speed = 115200
monitor_filters = esp32_exception_decoder ; Translates crash logs into readable line numbers
upload_speed = 921600                     ; Speeds up the flashing process

; --- MEMORY MAP (Do not touch) ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv ; UNLOCKS ALL 16MB OF FLASH

; --- NATIVE USB FLAGS ---
build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 
    -D LV_CONF_SKIP=1          ; Skips lv_conf.h
    -D LV_COLOR_DEPTH=16       ; Matches your QSPI display
    -D LV_COLOR_16_SWAP=0      ; Color format tweak
    -D LV_TICK_CUSTOM=1        ; Lets Arduino handle LVGL timing
; --- LIBRARIES ---
    -D LV_TICK_CUSTOM_SYS_TIME_EXPR=millis() ; Uses Arduino's millis() for LVGL timing
lib_deps =
    moononournation/GFX Library for Arduino @ ^1.5.0
    lvgl/lvgl @ ~8.3.11        ; Lock to v8.3 for stability